{
 "title": "{{component}}",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "CPU %",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100-(avg by (name) (floor(rate(node_cpu_seconds_total{mode=\"idle\",name=\"{{env}}-{{component}}\"}[1m]) * 100)))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 3, "y": 0 },
   "targets": [
    {
     "expr": "100-(avg by (name) (floor(rate(node_cpu_seconds_total{mode=\"idle\",name=\"{{env}}-{{component}}\"}[1m]) * 100)))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 0 },
   "targets": [
    {
     "expr": "node_memory_used_percent{name=\"{{env}}-{{component}}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Component Process",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_systemd_unit_state{name=\"{{env}}-{{component}}\",exported_name=\"{{service_name}}.service\",state=\"active\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}