- name: Install Nginx
  ansible.builtin.yum:
    name: nginx
    state: installed

- name: Remove Old HTTP Documents
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: Create a HTTP Document Directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory

#- name: Download and Extract Frontend App Content
#  ansible.builtin.unarchive:
#    src: https://roboshop-artifacts.s3.amazonaws.com/frontend.zip
#    dest: /usr/share/nginx/html
#    remote_src: yes

- name: Download & Extract {{component}} App Content
  ansible.builtin.unarchive:
    src: http://{{nexus_user}}:{{nexus_pass}}@172.31.40.116:8081/repository/{{component}}/{{component}}-{{app_version}}.zip
    dest: /usr/share/nginx/html
    remote_src: yes
  vars:
    nexus_user: "{{ lookup('aws_ssm', 'nexus.user', region='us-east-1') }}"
    nexus_pass: "{{ lookup('aws_ssm', 'nexus.pass', region='us-east-1') }}"

- name: Copy RoboShop Config file in Nginx
  ansible.builtin.template:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf

- name: Start Nginx Service
  ansible.builtin.systemd:
    state: restarted
    name: nginx
    enabled: yes
