- name: Install Nginx
  ansible.builtin.yum:
    name: nginx
    state: installed

- name: Remove Old HTTP Documents
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: Create a HTTP Document Directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory

- name: Download and Extract Frontend App Content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/frontend.zip
    dest: /usr/share/nginx/html
    remote_src: yes

- name: Remove Old Roboshop Config file
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: /etc/nginx/default.d/roboshop.conf

- name: Copy RoboShop Config file in Nginx
  ansible.builtin.copy:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf

- name: Start Nginx Service
  ansible.builtin.systemd:
    state: restarted
    name: nginx
    enabled: yes
