
#print_head "Copy Roboshop Nginx Config file"
#cp ${script_location}/files/roboshop.conf /etc/nginx/default.d/roboshop.conf &>>${LOG}
#status_check
#print_head "enable nginx"
#systemctl enable nginx &>>${LOG}
#status_check
#print_head "start nginx"
#systemctl restart nginx &>>${LOG}
#status_check

- name: Install Nginx
  ansible.builtin.yum:
    name: nginx
    state: installed

- name: Remove Old HTTP Documents
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: Create a HTTP Document Directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory

- name: Download and Extract Frontend App Content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/frontend.zip
    dest: /usr/share/nginx/html
    remote_src: yes


- name: Copy RoboShop Confile file in Nginx
  ansible.builtin.copy:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf