- name: Install GoLang
  ansible.builtin.yum:
    name: golang
    state: installed

- name: App-PreReq
  ansible.builtin.include_tasks: "app-prereq.yml"

- name: Download Dependencies
  ansible.builtin.shell: go mod init dispatch ; go get ; go build
  args:
    chdir: /app

- name: SystemD Setup
  ansible.builtin.include_tasks: "systemd.yml"

- name: Load Schema
  ansible.builtin.include_tasks: "{{schema_type}}-schema.yml"
  when: schema_load