#print_head "Install GoLang"
#yum install golang -y &>>${LOG}
#status_check
#
#APP_PREREQ
#
#print_head "Download the Dependencies."
#cd /app
#go mod init dispatch &>>${LOG}
#go get &>>${LOG}
#go build &>>${LOG}
#status_check
#
#print_head "Update Password in ${component} service file"
#sed -i -e "s/roboshop_rabbitmq_password/${roboshop_rabbitmq_password}/" ${script_location}/files/${component}.service
#status_check
#
#SYSTEMD_SETUP

- name: Install GoLang
  ansible.builtin.yum:
    name: golang
    state: installed

- name: App-PreReq
  ansible.builtin.include_tasks: "app-prereq.yml"

- name: Download Dependencies
  ansible.builtin.shell: go mod init dispatch ; go get ; go build
  args:
    chdir: /app

- name: App-PreReq
  ansible.builtin.include_tasks: "systemd.yml"