route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'email'
receivers:
  - name: "email"
    email_configs:
      - to: "rajasekhar1banda@gmail.com"
        from: "rajasekhar1banda@gmail.com"
        smarthost: "email-smtp.us-east-1.amazonaws.com:587"  # smtp endpoint
        auth_username: "{{ lookup('aws_ssm', 'ses.user', region='us-east-1') }}"           # smtp username & password
        auth_password: "{{ lookup('aws_ssm', 'ses.pass', region='us-east-1') }}"
        require_tls: true
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
